apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: foos.ack.pandaria.io
spec:
  group: ack.pandaria.io
  names:
    kind: Foo
    plural: foos
    shortNames:
    - ackcc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            deploymentName:
              nullable: true
              type: string
            replicas:
              nullable: true
              type: integer
          type: object
        status:
          properties:
            availableReplicas:
              type: integer
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
